//
//  ListLicensesPresenter.swift
//  Relationship
//
//  Created by Raymond Law on 9/16/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListLicensesPresentationLogic
{
  func presentNavBarTitle(response: ListLicenses.SetNavBarTitle.Response)
  func presentFetchedLicenses(response: ListLicenses.FetchLicenses.Response)
  func presentCreatedLicense(response: ListLicenses.CreateLicense.Response)
  func presentDeletedLicense(response: ListLicenses.DeleteLicense.Response)
}

class ListLicensesPresenter: ListLicensesPresentationLogic
{
  weak var viewController: ListLicensesDisplayLogic?
  
  // MARK: Set nav bar title
  
  func presentNavBarTitle(response: ListLicenses.SetNavBarTitle.Response)
  {
    let title = response.customerName ?? "Select a customer"
    let viewModel = ListLicenses.SetNavBarTitle.ViewModel(title: title)
    viewController?.displayNavBarTitle(viewModel: viewModel)
  }
  
  // MARK: Fetch licenses
  
  func presentFetchedLicenses(response: ListLicenses.FetchLicenses.Response)
  {
    let displayedLicenses = response.licenses.map { formatLicense(license: $0) }
    let viewModel = ListLicenses.FetchLicenses.ViewModel(displayedLicenses: displayedLicenses)
    viewController?.displayFetchedLicenses(viewModel: viewModel)
  }
  
  // MARK: Create license
  
  func presentCreatedLicense(response: ListLicenses.CreateLicense.Response)
  {
    let displayedLicenses = response.licenses.map { formatLicense(license: $0) }
    let viewModel = ListLicenses.CreateLicense.ViewModel(displayedLicenses: displayedLicenses)
    viewController?.displayCreatedLicense(viewModel: viewModel)
  }
  
  // MARK: Delete license
  
  func presentDeletedLicense(response: ListLicenses.DeleteLicense.Response)
  {
    let displayedLicenses = response.licenses.map { formatLicense(license: $0) }
    let viewModel = ListLicenses.DeleteLicense.ViewModel(displayedLicenses: displayedLicenses)
    viewController?.displayDeletedLicense(viewModel: viewModel)
  }
  
  // MARK: Format license
  
  private func formatLicense(license: License) -> ListLicenses.DisplayedLicense
  {
    return ListLicenses.DisplayedLicense(serial: license.serial)
  }
}
