//
//  ListLicensesRouter.swift
//  Relationship
//
//  Created by Raymond Law on 9/16/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListLicensesRoutingLogic
{
}

protocol ListLicensesDataPassing
{
  var dataStore: ListLicensesDataStore? { get }
}

class ListLicensesRouter: NSObject, ListLicensesRoutingLogic, ListLicensesDataPassing
{
  weak var viewController: ListLicensesViewController?
  var dataStore: ListLicensesDataStore?
  
  // MARK: Routing
  
  // MARK: Navigation
  
  // MARK: Passing data
}
