//
//  ListLicensesModels.swift
//  Relationship
//
//  Created by Raymond Law on 9/16/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListLicenses
{
  struct DisplayedLicense
  {
    var serial: String
  }
  
  // MARK: Use cases
  
  enum SetNavBarTitle
  {
    struct Request
    {
    }
    struct Response
    {
      var customerName: String?
    }
    struct ViewModel
    {
      var title: String
    }
  }
  
  enum FetchLicenses
  {
    struct Request
    {
    }
    struct Response
    {
      var licenses: [License]
    }
    struct ViewModel
    {
      var displayedLicenses: [DisplayedLicense]
    }
  }
  
  enum CreateLicense
  {
    struct Request
    {
      var id: String
      var serial: String
    }
    struct Response
    {
      var licenses: [License]
    }
    struct ViewModel
    {
      var displayedLicenses: [DisplayedLicense]
    }
  }
  
  enum DeleteLicense
  {
    struct Request
    {
      var indexPath: IndexPath
    }
    struct Response
    {
      var licenses: [License]
    }
    struct ViewModel
    {
      var displayedLicenses: [DisplayedLicense]
    }
  }
}
